version: '3.7'

services:

    appDB:
      image: mariadb
      container_name: appDB
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=LIVRARIA
      ports:
        - 3306:3306

      
    app:
        container_name: app
        build:
          context: .
          dockerfile: ./Dockerfile
        image: livraria
        ports:
          - 3000:3000
        depends_on:
          - appDB